#ifndef __wxprintgp__
#define __wxprintgp__

/**
@file
Subclass of View_PrintGP, which is generated by wxFormBuilder.
*/

#include "wxinterface.h"
#include "icpdfrm.h"

#include <string>
using std::string;
#include <iomanip>


class IcpdFrm;

/** Implementing View_PrintGP */
class WxPrintGP : public View_PrintGP
{
private:
	IcpdFrm* currentFrmwork;
	
protected:
	// Handlers for View_PrintGP events.
	void PressedKey( wxKeyEvent& event );
	//void applyButtonEvt( wxCommandEvent& event );
	void okButtonEvt( wxCommandEvent& event );
	void cancelButtonEvt( wxCommandEvent& event );
	void ok();
	void cancel();
	
public:
	/** Constructor */
	WxPrintGP( IcpdFrm* frmwork );
	
	void refresh();
	string doubleToString(double val);
};


#endif // __wxprintgp__
